name: todo_riv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  gap: ^3.0.1

flutter:
  uses-material-design: true
